name: actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
          echo "{{ github }}"
          echo "=========="
          echo $GITHUB
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -a
      - name: simple github actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: mrxrinc
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
