name: actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple github actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: mrxrinc
      - name: log greeting time
        run: echo ${{steps.greet.outputs.time}}
