name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.15
    steps:
      - name: log node version and os
        run: |
          node -v
          cat /etc/os-release
